### ISSUE TITLE
Validation issues detected by the GBIF validator

### ISSUE THREAD

**Issue by tomgilissen** [naturalis/DWCAConfig#92]
Hi @jeroencreuwels,

Just fyi, the Gbif data validator warns that (among some other minor issues) the EML document belonging to Xeno-canto (https://github.com/naturalis/DWCAConfig/blob/master/specimen/wildlife-sounds/eml.xml) does not validate against the schema. Checkout for more details: https://www.gbif.org/tools/data-validator/e5d1e95d-4edc-4a03-ab27-17d2d9e705a7

Best wishes,

Tom

**Comment by jeroencreuwels** [comment]
I have seen these warning before, but they don't seem critical. I have no idea why they do not validate against the schema. I will ask GBIF what is going on. Jeroen

**Comment by jeroencreuwels** [comment]
I received feedback from GBIF:
 "It looks like the EML document uses a version that we don’t support yet (we support version 1.0, 1.0.1, 1.0.2 and 1.1: see https://github.com/gbif/gbif-data-validator/issues/98#issuecomment-1118411236). This is likely the reason why the validator gives all those warnings.

The publishers could use one of the versions supported instead. Alternatively, they could ignore those warnings (but not all the metadata will be interpreted)."
